import path from "path";
import createServerApp from "./createApp";
import appRoutes from "../routes/routes";

const requestHandler = (req, res) => {
  // We pass store to renderer
  // const promises = fetchServerData(req, store)
  // Wait for all the loadData functions, if they are resolved, send the rendered html to browser.
  // Promise.all(promises).then(() => {

  // This is the stats file generated by webpack loadable plugin
  const statsFile = path.resolve("dist/client/loadable-stats.json");
  const context = {};
  const markup = createServerApp(context, req.url, statsFile)(appRoutes);

  if (context.url) {
    res.redirect(context.url);
  } else {
    res.status(200).send(markup);
  }

  // });
};

export default requestHandler;
