version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  checks:
    description: "Install node checkout code and install dependencies"
    executor:
      name: node/default
      tag: 12.16.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "CSS Linting"
          command: yarn lint:css
      - run:
          name: "JS Linting"
          command: yarn lint:js
      - run:
          name: "Testing"
          command: yarn test
workflows:
    check-code:
      jobs:
        - checks
